### ISSUE TITLE
Appears that chromium isn't installing correctly

### ISSUE THREAD

**Issue by souldessin** [YunoHost-Apps/linkwarden_ynh#10]
I recently installed YunoHost on my a fresh Debian 12 and everything else is working correctly, but I can't get Linkwarden to preserver my links. When looking at the logs, I have the below error for every link that I imported.

```log
Nov 24 14:41:25 yarn[645140]: [1] Error processing link https://www.instructables.com/Wood-Bowl-no-Lathe-No-Problem/ for user 1: browserType.launch: Executable doesn't exist at /var/www/linkwarden/.cache/ms-playwright/chromium-1124/chrome-linux/chrome
Nov 24 14:41:25 yarn[645140]: [1] ╔═════════════════════════════════════════════════════════════════════════╗
Nov 24 14:41:25 yarn[645140]: [1] ║ Looks like Playwright Test or Playwright was just installed or updated. ║
Nov 24 14:41:25 yarn[645140]: [1] ║ Please run the following command to download new browsers:              ║
Nov 24 14:41:25 yarn[645140]: [1] ║                                                                         ║
Nov 24 14:41:25 yarn[645140]: [1] ║     yarn playwright install                                             ║
Nov 24 14:41:25 yarn[645140]: [1] ║                                                                         ║
Nov 24 14:41:25 yarn[645140]: [1] ║ <3 Playwright Team                                                      ║
Nov 24 14:41:25 yarn[645140]: [1] ╚═════════════════════════════════════════════════════════════════════════╝
Nov 24 14:41:25 yarn[645140]: [1]     at archiveHandler (/var/www/linkwarden/lib/api/archiveHandler.ts:50:34)
Nov 24 14:41:25 yarn[645140]: [1]     at archiveLink (/var/www/linkwarden/scripts/worker.ts:112:27)
Nov 24 14:41:25 yarn[645140]: [1]     at /var/www/linkwarden/scripts/worker.ts:133:17
Nov 24 14:41:25 yarn[645140]: [1]     at processBatch (/var/www/linkwarden/scripts/worker.ts:133:6)
Nov 24 14:41:25 yarn[645140]: [1]     at async init (/var/www/linkwarden/scripts/worker.ts:148:7) {
Nov 24 14:41:25 yarn[645140]: [1]   name: 'Error'
Nov 24 14:41:25 yarn[645140]: [1] }
```

I did try running both `yarn playwright install` & `yarn playwright install chromium` in the `/var/www/linkwarden/` directory.

|  |  |
| --- | :---: |
| **YunoHost Version** | 12.0.7 |
| **Installed On** | Debian 12 via install script |
| **Linkwarden Version** | 2.8.3~ynh1 |

---

Lastly, loving the system. It's nicer than managing a million dockers or VMs.

**Comment by Jolg42** [comment]
I encountered the same issue and when I ran the command `yarn playwright install` it showed another error about "Missing libraries" 😄 

```
yarn playwright install
yarn run v1.22.22
$ /var/www/linkwarden/node_modules/.bin/playwright install
Downloading Firefox 127.0 (playwright build v1454) from https://playwright.azureedge.net/builds/firefox/1454/firefox-debian-12.zip
86.6 MiB [====================] 100% 0.0s
Firefox 127.0 (playwright build v1454) downloaded to /root/.cache/ms-playwright/firefox-1454
Downloading Webkit 17.4 (playwright build v2035) from https://playwright.azureedge.net/builds/webkit/2035/webkit-debian-12.zip
86 MiB [====================] 100% 0.0s
Webkit 17.4 (playwright build v2035) downloaded to /root/.cache/ms-playwright/webkit-2035
Playwright Host validation warning:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgstreamer-1.0.so.0                            ║
║     libwoff2dec.so.1.0.2                             ║
║     libgstallocators-1.0.so.0                        ║
║     libgstapp-1.0.so.0                               ║
║     libgstbase-1.0.so.0                              ║
║     libgstpbutils-1.0.so.0                           ║
║     libgstaudio-1.0.so.0                             ║
║     libgsttag-1.0.so.0                               ║
║     libgstvideo-1.0.so.0                             ║
║     libgstgl-1.0.so.0                                ║
║     libgstcodecparsers-1.0.so.0                      ║
║     libgstfft-1.0.so.0                               ║
║     libwebpdemux.so.2                                ║
║     libharfbuzz-icu.so.0                             ║
║     libenchant-2.so.2                                ║
║     libhyphen.so.0                                   ║
║     libmanette-0.2.so.0                              ║
╚══════════════════════════════════════════════════════╝
```


I tried solving this by running:
```sh
su
cd /var/www/linkwarden/
yarn playwright install --with-deps chromium
systemctl restart linkwarden
```

But it looked like it the lcoation of the chromium was not right so I tried copying it
```
cp -R /root/.cache/ms-playwright/ .cache/ms-playwright/
systemctl restart linkwarden
```

Now I get this error unfortunately and I'm giving up on this 😓 
```
[0100/000000.267375:ERROR:zygote_linux.cc(639)] Zygote could not fork: process_type gpu-process numfds 3 child_pid -1
2025-09-20T09:12:12.304315+02:00 yunohost yarn[111536]: [1] [pid=111605][err] [0100/000000.267436:ERROR:zygote_linux.cc(671)] write: Broken pipe (32)
```

Full logs from `/var/log/syslog`:
Found by running `grep -nr 'zygote_communication_linux*' /var/log/`
```
2025-09-20T09:12:08.846087+02:00 yunohost systemd[1]: Started linkwarden.service - Linkwarden: collaborative bookmark manager.
2025-09-20T09:12:09.079964+02:00 yunohost yarn[111513]: yarn run v1.22.22
2025-09-20T09:12:09.115341+02:00 yunohost yarn[111513]: $ concurrently -P "next start {@}" "yarn worker:prod" --
2025-09-20T09:12:09.486429+02:00 yunohost yarn[111536]: [0] - ready started server on 0.0.0.0:47688, url: http://localhost:47688
2025-09-20T09:12:09.537662+02:00 yunohost yarn[111536]: [1] $ ts-node --transpile-only --skip-project scripts/worker.ts
2025-09-20T09:12:09.592846+02:00 yunohost yarn[111536]: [0] - #033[36minfo#033[39m Loaded env from /var/www/linkwarden/.env
2025-09-20T09:12:11.279809+02:00 yunohost yarn[111536]: [1] #033[34mInitializing the worker...#033[0m
2025-09-20T09:12:11.280298+02:00 yunohost yarn[111536]: [1] #033[34mStarting RSS polling...#033[0m
2025-09-20T09:12:11.280326+02:00 yunohost yarn[111536]: [1] #033[34mStarting link preservation...#033[0m
2025-09-20T09:12:11.384438+02:00 yunohost yarn[111536]: [1] #033[34mProcessing link place:parent=menu________&parent=unfiled_____&parent=toolbar_____&queryType=1&sort=12&maxResults=10&excludeQueries=1 for user 1#033[0m
2025-09-20T09:12:11.393503+02:00 yunohost yarn[111536]: [1] #033[34mProcessing link javascript:if(top['bookmarklet-url@wallabag.org']){top['bookmarklet-url@wallabag.org'];}else{(function(){var%20url%20=%20location.href%20||%20url;window.open('https://framabag.org/u/jolg42/?action=add&autoclose=true&url='%20+%20btoa(url),'_blank');})();void(0);} for user 1#033[0m
2025-09-20T09:12:11.394233+02:00 yunohost yarn[111536]: [1] #033[34mProcessing link https://github.com/josh-berry/tab-stash/wiki/Exporting-Tabs-from-Tab-Stash for user 1#033[0m
2025-09-20T09:12:11.394732+02:00 yunohost yarn[111536]: [1] #033[34mProcessing link https://josh-berry.github.io/tab-stash/tips.html for user 1#033[0m
2025-09-20T09:12:11.395433+02:00 yunohost yarn[111536]: [1] #033[34mProcessing link https://addons.mozilla.org/en-US/firefox/addon/tab-stash/ for user 1#033[0m
2025-09-20T09:12:12.294226+02:00 yunohost yarn[111536]: [1] #033[34mError processing link place:parent=menu________&parent=unfiled_____&parent=toolbar_____&queryType=1&sort=12&maxResults=10&excludeQueries=1 for user 1:#033[0m browserType.launch: Target page, context or browser has been closed
2025-09-20T09:12:12.298013+02:00 yunohost yarn[111536]: [1] Browser logs:
2025-09-20T09:12:12.298061+02:00 yunohost yarn[111536]: [1]
2025-09-20T09:12:12.298096+02:00 yunohost yarn[111536]: [1] <launching> /var/www/linkwarden/.cache/ms-playwright/chromium-1124/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --enable-gpu --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-fWmWQG --remote-debugging-pipe --no-startup-window
2025-09-20T09:12:12.299468+02:00 yunohost yarn[111536]: [1] <launched> pid=111605
2025-09-20T09:12:12.300619+02:00 yunohost yarn[111536]: [1] [pid=111605][err] [0920/091211.656795:ERROR:zygote_communication_linux.cc(164)] Did not receive ping from zygote child
2025-09-20T09:12:12.300818+02:00 yunohost yarn[111536]: [1] [pid=111605][err] [0920/091211.656830:FATAL:zygote_communication_linux.cc(165)] Check failed: false.
2025-09-20T09:12:12.300862+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #0 0x5e6b742588e2 base::debug::CollectStackTrace()
2025-09-20T09:12:12.300891+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #1 0x5e6b74245cde base::debug::StackTrace::StackTrace()
2025-09-20T09:12:12.301050+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #2 0x5e6b7419ce3a logging::LogMessage::Flush()
2025-09-20T09:12:12.301301+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #3 0x5e6b7419cd1d logging::LogMessage::~LogMessage()
2025-09-20T09:12:12.301433+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #4 0x5e6b741861c0 logging::(anonymous namespace)::NotReachedLogMessage::~NotReachedLogMessage()
2025-09-20T09:12:12.301593+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #5 0x5e6b7418621e logging::(anonymous namespace)::NotReachedLogMessage::~NotReachedLogMessage()
2025-09-20T09:12:12.302438+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #6 0x5e6b74185c73 logging::CheckError::~CheckError()
2025-09-20T09:12:12.302459+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #7 0x5e6b71b5f87c content::ZygoteCommunication::ForkRequest()
2025-09-20T09:12:12.302736+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #8 0x5e6b724693ce content::internal::ChildProcessLauncherHelper::LaunchProcessOnLauncherThread()
2025-09-20T09:12:12.302768+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #9 0x5e6b71d268ec content::internal::ChildProcessLauncherHelper::LaunchOnLauncherThread()
2025-09-20T09:12:12.302795+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #10 0x5e6b741eaeef base::TaskAnnotator::RunTaskImpl()
2025-09-20T09:12:12.303098+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #11 0x5e6b7420dfc7 base::internal::TaskTracker::RunTaskImpl()
2025-09-20T09:12:12.303130+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #12 0x5e6b7420e0b1 base::internal::TaskTracker::RunBlockShutdown()
2025-09-20T09:12:12.303157+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #13 0x5e6b7420dd4e base::internal::TaskTracker::RunTask()
2025-09-20T09:12:12.303184+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #14 0x5e6b7420d8c0 base::internal::TaskTracker::RunAndPopNextTask()
2025-09-20T09:12:12.303546+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #15 0x5e6b7421f988 base::internal::WorkerThread::RunWorker()
2025-09-20T09:12:12.303582+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #16 0x5e6b7421f64d base::internal::WorkerThread::RunDedicatedWorker()
2025-09-20T09:12:12.303704+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #17 0x5e6b7421f52b base::internal::WorkerThread::ThreadMain()
2025-09-20T09:12:12.303721+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #18 0x5e6b7423c2ea base::(anonymous namespace)::ThreadFunc()
2025-09-20T09:12:12.303735+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #19 0x753e610621f5 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x891f4)
2025-09-20T09:12:12.303755+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #20 0x753e610e1b40 __clone
2025-09-20T09:12:12.304234+02:00 yunohost yarn[111536]: [1] [pid=111605][err] Task trace:
2025-09-20T09:12:12.304257+02:00 yunohost yarn[111536]: [1] [pid=111605][err] #0 0x5e6b71d26308 content::internal::ChildProcessLauncherHelper::StartLaunchOnClientThread()
2025-09-20T09:12:12.304271+02:00 yunohost yarn[111536]: [1] [pid=111605][err]
2025-09-20T09:12:12.304299+02:00 yunohost yarn[111536]: [1] [pid=111605][err] [0100/000000.267375:ERROR:zygote_linux.cc(639)] Zygote could not fork: process_type gpu-process numfds 3 child_pid -1
2025-09-20T09:12:12.304315+02:00 yunohost yarn[111536]: [1] [pid=111605][err] [0100/000000.267436:ERROR:zygote_linux.cc(671)] write: Broken pipe (32)
2025-09-20T09:12:12.304329+02:00 yunohost yarn[111536]: [1] [pid=111605] <process did exit: exitCode=null, signal=SIGTRAP>
2025-09-20T09:12:12.304344+02:00 yunohost yarn[111536]: [1] [pid=111605] starting temporary directories cleanup
```

**Comment by Jolg42** [comment]
But what I did should not be needed since it's already done in https://github.com/YunoHost-Apps/linkwarden_ynh/blob/master/scripts/install#L61 

@ericgaspar any idea about this? At the moment, in the current state, it looks to me like this app is not functioning like expected.

Note: I'm new to Yunohost and happy to help

[Off-topic, not Yunohost related]
I tried to install it via a [Proxmox VE Helper script](https://community-scripts.github.io/ProxmoxVE/scripts?id=linkwarden&category=Documents%20%26%20Notes) and it worked out of the box so far, the headless browser is doing screenshots in the background
It's a newer version of Linkwarden (2.12)
I noticed that the current version in 2.10 (https://github.com/YunoHost-Apps/linkwarden_ynh/blob/master/manifest.toml#L48) in Yunohost since it does not show "Import Pocket" when I tried to import bookmarks
